server:
  port: 8085

spring:
  application:
    name: billing-service

  config:
    import: "optional:consul:, vault://"
  cloud:
    vault:
      token: hvs.l9lGujLVbLlfH9Pk5WWDmzxg
      scheme: http
      kv:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
