server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///home/arrhioui/Documents/S5/1-DD/Recap/E-Com/global-app-config

